info:
  name: '@project.parent.name@'
  version: '@project.version@'

server:
  address: 0.0.0.0
  servlet:
    context-path: /
  port: 6060

management:
  endpoints.web:
    exposure.include: '*'
  health:
    jms:
      enabled: false
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    binders:
      enabled: true
  server:
    address: 0.0.0.0
    port: 6061
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enable: true
    prometheus:
      enable: true
    health:
      show-details: always
      probes:
        enabled: true

spring:
  cloud:
    stream:
#      default-binder: kafkaSource
      function:
        definition: sendData;processAvro;processProto
      bindings:
        processProto-in-0:
          destination: OrdersInput-proto
          binder: kafkaKstream
        processProto-in-1:
          destination: EnabledCustomer-proto
          binder: globalktable
        processProto-out-0:
          destination: OrdersOutput-proto
          binder: kafkaKstream
        processAvro-in-0:
          destination: OrdersInput-avro
          binder: kafkaKstream
        processAvro-in-1:
          destination: EnabledCustomer-proto
          binder: globalktable
        processAvro-out-0:
          destination: OrdersOutput-avro
          binder: kafkaKstream
        sendData-in-0:
          destination: EnabledCustomer-proto
          binder: kafkaSource
          group: ksp-consent-service-two-binder-proto
          contentType: application/x-protobuf
        sendData-out-0:
          destination: EnabledCustomer-proto-out
          binder: kafkaTarget
          contentType: application/x-protobuf
      binders:
        kafkaSource:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder:
              brokers: localhost:9092
              configuration:
                value.deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
              consumer-properties:
                schema.registry.url: http://localhost:8081
                derive.type: true

        kafkaTarget:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder:
              brokers: localhost:9092
              configuration:
                value.serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
              producer-properties:
                schema.registry.url: http://localhost:8081
                derive.type: true

        kafkaKstream:
          type: kstream
          environment:
            spring.cloud.stream.kafka.stream.binder:
                brokers: localhost:9092
                configuration:
                  schema.registry.url: http://localhost:8081
        globalktable:
          type: globalktable
          environment:
            spring.cloud.stream.kafka.streams.binder:
              brokers: localhost:9092
              configuration:
                default.value.serde: io.confluent.kafka.streams.serdes.protobuf.KafkaProtobufSerde
                schema.registry.url: http://localhost:8081
                derive.type: true
      kafka:
        streams:
          binder:
            deserialization-exception-handler: sendtodlq
            functions:
              processProto.applicationId: spring-cloud-kafka-streams-stream-globalktable-processProto
              processAvro.applicationId: spring-cloud-kafka-streams-stream-globalktable-processAvro
#            brokers: localhost:9092
            configuration:
              state.dir: state-store
              acceptable.recovery.lag: 0
              schema.registry.url: http://localhost:8081
          bindings:
            processProto-in-0:
              consumer:
                value-serde: io.confluent.kafka.streams.serdes.protobuf.KafkaProtobufSerde
                configuration:
                  derive.type: true
            processProto-in-1:
              consumer:
                value-serde: io.confluent.kafka.streams.serdes.protobuf.KafkaProtobufSerde
                configuration:
                  derive.type: true
            processProto-out-0:
              producer:
                value-serde: io.confluent.kafka.streams.serdes.protobuf.KafkaProtobufSerde
                configuration:
                  derive.type: true
            processAvro-in-0:
              consumer:
                value-serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                configuration:
                  specific.avro.reader: true
            processAvro-in-1:
              consumer:
                value-serde: io.confluent.kafka.streams.serdes.protobuf.KafkaProtobufSerde
                configuration:
                  derive.type: true
            processAvro-out-0:
              producer:
                value-serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                configuration:
                  specific.avro.reader: true
        binder:
          configuration:
            heartbeat.interval.ms: 10000
            max.poll.records: 5000

logging.level:
  root: info
  debug: false
